---INTERNATIONAL AUTHORITY COALITION. 

--- ALL RIGHTS RESERVED. CONFIDENTIAL AND PROPRIETARY.
--- IAC/bg.lua
--- BLACKLISTED GROUPS


local blacklistedgroups = {
   [9327275] = true, -- Zoger SCPF
}
