---INTERNATIONAL AUTHORITY COALITION. 

--- ALL RIGHTS RESERVED. CONFIDENTIAL AND PROPRIETARY.
--- IAC/bg.lua
--- BLACKLISTED GROUPS


local Reports = {
  blacklistedgroup = {  
   5515777500, --INTEL_DECLENSION
  },
}
